sudo: required
python: 3.6

language: C


matrix:
  include:
    - compiler: gcc
      before_script:
        - sudo apt-get -qq update
        - sudo apt-get install -y python3-numpy python3-sphinx
      script:
        - ./configure
        - make check
        - python3 setup.py module
        - python3 setup.py test
        - python3 setup.py doctest

    - compiler: gcc
      before_script:
        - sudo apt-get -qq update
        - sudo apt-get install -y valgrind
      script:
        - ./configure --with-valgrind
        - make parser
        - make memcheck
        - python3 setup.py module
        - python3 setup.py test

    - compiler: clang
      before_script:
        - export CC=clang
      script:
        - ./configure
        - make parser
        - make check
        - python3 setup.py module
        - python3 setup.py test

    - language: objective-c
      os: osx
      compiler: clang
      before_install:
        - brew install python3
      before_script:
        - export CC=clang
      script:
        - ./configure
        - make check
        - python3 setup.py module
        - python3 setup.py test

    - compiler: gcc
      script:
        - python3 setup.py build
        - python3 setup.py test

    - compiler: conda
      install:
        - cd ..
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
        - bash Miniconda3-latest-Linux-x86_64.sh -b
        - export PATH=$HOME/miniconda3/bin:$PATH
        - conda update --yes conda
        - conda install --yes conda-build=3.3.0
        - conda install --yes anaconda-client
      script:
        - cd ndtypes
        - git fetch --unshallow
        - conda build .conda/libndtypes
        - conda build .conda/ndtypes
        - export LIBNDTYPES=`conda build --output .conda/libndtypes`
        - export NDTYPES=`conda build --output .conda/ndtypes`
        - if test X"$TRAVIS_BRANCH" = X"master" && test X"$TRAVIS_PULL_REQUEST" = X"false"; then anaconda --token $ANACONDA_TOKEN upload $LIBNDTYPES --user xnd --label dev; fi
        - if test X"$TRAVIS_BRANCH" = X"master" && test X"$TRAVIS_PULL_REQUEST" = X"false"; then anaconda --token $ANACONDA_TOKEN upload $NDTYPES --user xnd --label dev; fi

    - language: objective-c
      os: osx
      compiler: conda
      install:
        - cd ..
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
        - bash Miniconda3-latest-MacOSX-x86_64.sh -b
        - export PATH=$HOME/miniconda3/bin:$PATH
        - export CC=clang
        - conda update --yes conda
        - conda install --yes conda-build=3.3.0
        - conda install --yes anaconda-client
      script:
        - cd ndtypes
        - git fetch --unshallow
        - conda build .conda/libndtypes
        - conda build .conda/ndtypes
        - export LIBNDTYPES=`conda build --output .conda/libndtypes`
        - export NDTYPES=`conda build --output .conda/ndtypes`
        - if test X"$TRAVIS_BRANCH" = X"master" && test X"$TRAVIS_PULL_REQUEST" = X"false"; then anaconda --token $ANACONDA_TOKEN upload $LIBNDTYPES --user xnd --label dev; fi
        - if test X"$TRAVIS_BRANCH" = X"master" && test X"$TRAVIS_PULL_REQUEST" = X"false"; then anaconda --token $ANACONDA_TOKEN upload $NDTYPES --user xnd --label dev; fi

env:
  global:
    - secure: "IMucUmJjleiduTI+XFbkecNNZaJC8m1ksxl5oG7FLpgyRoDvK9xSLtutXCoov6EfF9JBX1ARCS5Gl5NJwH3P8T9Sp2bZgGrjzfwMGg7ZPtLTrY2eZIuVxya3/62ZGIwGfPiHiGQ1lsyZEtmTYxBTuGnakJJOP5XHDN9jHxnjmm9O9SYtz4kKmHZi7+QmYhEkdvGolEDo5oqAkkU6pw1H+Ux5N1TPhRD+IUwnCmpS7i7l9dEG/hu49Suld2cxorcvoruScJbbAfoGabLveBmwOJnjt1lRYH2DPGUolhO8/FNZGK/brQkaInEmXeyMpaXzvh7eHvw6YdzkDBZuZ5RNKPFIxJLsuO4f95f+YiyYI1RUk7b98X8rQK9UnzMRjS4DIX1c/8ncT1Mn4BYkqkgyrAqPYIAITAcYdmK9W4edmlMr4EnqS5r3yDSdUDaqFZf5TfU5+B0qZYkBCqodnzBJ9L2x3U6cHG+EHRG+yW5iKwYSyqi+KYNMQSqSy5zH80FDEMYnTf5AhPkZH9vSXP5oCNgP/bGSZvD/qnfOT/Xci9u+0AoSaBDuC5T4c1M0ACNsTQqVKxYbxYdOgOdkJsvV8fVibIQzeLpaJv8Op4KQ4nOWQYhEaKiHlfRp2tNoeUXnedWcSwI4E4+LE8lQi/aUe9+XFh/xIQnm5Ehw8gT2Pik="
